# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b411fe7c9be9e6b4c42c74effd5f7fd0db46ce05d1a5f709c282fdba7693cc139a765830d76a7b5e9ffb97e8a68ffcf1dac76445321b82391caa308ce6699fd4

test:
  secret_key_base: d2517503a5360100e20c1e5caffe26f0595235c3d7be1eed471985382f11647dd454bb2cf9510d5707cd1b81aea3dada2a8f81436eed20ebca0d38e8347fc1c8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
